In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("netflix_titles.csv")

In [3]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [4]:
df.shape

(8807, 12)

In [6]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [11]:
df["rating"].value_counts()

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

In [14]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [17]:
df["type"].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [23]:
df.groupby("type")["rating"].sum()

type
Movie      PG-13PGTV-MAPG-13TV-MATV-PGTV-MATV-14TV-PGTV-Y...
TV Show    TV-MATV-MATV-MATV-MATV-MATV-14TV-MATV-MATV-MAT...
Name: rating, dtype: object

In [24]:
df["director"] = df["director"].fillna("Unknown")

In [40]:
df["duration"] = df["duration"].fillna("Not Available")

C:\Users\Abhay\AppData\Local\Temp\ipykernel_17136\4180364055.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["duration"] = df["duration"].fillna("Not Available")

In [26]:
df["cast"] = df["cast"].fillna("Not Available")
df["country"] = df["country"].fillna("Unknown")

In [27]:
df["date_added"] = df["date_added"].str.strip()
df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")

In [30]:
df["date_added"].isnull().sum()

np.int64(0)

In [29]:
df = df.dropna(subset=["date_added"])

In [31]:
df["year_added"] = df["date_added"].dt.year
df["month_added"] = df["date_added"].dt.month

C:\Users\Abhay\AppData\Local\Temp\ipykernel_17136\3618497778.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["year_added"] = df["date_added"].dt.year
C:\Users\Abhay\AppData\Local\Temp\ipykernel_17136\3618497778.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["month_added"] = df["date_added"].dt.month

In [32]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not Available,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,9
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,9
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,9
3,s4,TV Show,Jailbirds New Orleans,Unknown,Not Available,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,9
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",2019,11
8803,s8804,TV Show,Zombie Dumb,Unknown,Not Available,Unknown,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",2019,7
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,2019,11
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",2020,1
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019,3

In [41]:
df["duration_int"] = df["duration"].str.extract("(\d+)")
df["duration_int"] = pd.to_numeric(df["duration_int"])

C:\Users\Abhay\AppData\Local\Temp\ipykernel_17136\2908065007.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["duration_int"] = df["duration"].str.extract("(\d+)")
C:\Users\Abhay\AppData\Local\Temp\ipykernel_17136\2908065007.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["duration_int"] = pd.to_numeric(df["duration_int"])

In [42]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,duration_int
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not Available,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,9,90.0
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,9,2.0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,9,1.0
3,s4,TV Show,Jailbirds New Orleans,Unknown,Not Available,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,9,1.0
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,9,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",2019,11,158.0
8803,s8804,TV Show,Zombie Dumb,Unknown,Not Available,Unknown,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",2019,7,2.0
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,2019,11,88.0
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",2020,1,88.0
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019,3,111.0

In [43]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
year_added      0
month_added     0
duration_int    3
dtype: int64

In [36]:
df["rating"] = df["rating"].fillna(df["rating"].mode()[0])

C:\Users\Abhay\AppData\Local\Temp\ipykernel_17136\4062337860.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["rating"] = df["rating"].fillna(df["rating"].mode()[0])

In [44]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
year_added      0
month_added     0
duration_int    3
dtype: int64

In [46]:
df.shape

(8797, 15)

In [47]:
df["listed_in"] = df["listed_in"].str.split(", ")
df_genre = df.explode("listed_in")

C:\Users\Abhay\AppData\Local\Temp\ipykernel_17136\853337595.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["listed_in"] = df["listed_in"].str.split(", ")

In [49]:
df_genre["country"] = df_genre["country"].str.split(", ")
df_final = df_genre.explode("country")

In [58]:
columns_to_keep = [
    "show_id",
    "type",
    "title",
    "country",
    "release_year",
    "year_added",
    "month_added",
    "rating",
    "duration_int",
    "listed_in"
]

df_clean = df_final[columns_to_keep]

In [59]:
df_clean

,show_id,type,title,country,release_year,year_added,month_added,rating,duration_int,listed_in
0,s1,Movie,Dick Johnson Is Dead,United States,2020,2021,9,PG-13,90.0,Documentaries
1,s2,TV Show,Blood & Water,South Africa,2021,2021,9,TV-MA,2.0,International TV Shows
1,s2,TV Show,Blood & Water,South Africa,2021,2021,9,TV-MA,2.0,TV Dramas
1,s2,TV Show,Blood & Water,South Africa,2021,2021,9,TV-MA,2.0,TV Mysteries
2,s3,TV Show,Ganglands,Unknown,2021,2021,9,TV-MA,1.0,Crime TV Shows
...,...,...,...,...,...,...,...,...,...,...
8805,s8806,Movie,Zoom,United States,2006,2020,1,PG,88.0,Children & Family Movies
8805,s8806,Movie,Zoom,United States,2006,2020,1,PG,88.0,Comedies
8806,s8807,Movie,Zubaan,India,2015,2019,3,TV-14,111.0,Dramas
8806,s8807,Movie,Zubaan,India,2015,2019,3,TV-14,111.0,International Movies
8806,s8807,Movie,Zubaan,India,2015,2019,3,TV-14,111.0,Music & Musicals

In [60]:
df_clean.columns = [
    "Show_ID",
    "Type",
    "Title",
    "Country",
    "Release_Year",
    "Year_Added",
    "Month_Added",
    "Rating",
    "Duration",
    "Genre"
]

In [63]:
df_clean.to_csv("fact_table.csv", index=False)

In [62]:
df_clean

,Show_ID,Type,Title,Country,Release_Year,Year_Added,Month_Added,Rating,Duration,Genre
0,s1,Movie,Dick Johnson Is Dead,United States,2020,2021,9,PG-13,90.0,Documentaries
1,s2,TV Show,Blood & Water,South Africa,2021,2021,9,TV-MA,2.0,International TV Shows
1,s2,TV Show,Blood & Water,South Africa,2021,2021,9,TV-MA,2.0,TV Dramas
1,s2,TV Show,Blood & Water,South Africa,2021,2021,9,TV-MA,2.0,TV Mysteries
2,s3,TV Show,Ganglands,Unknown,2021,2021,9,TV-MA,1.0,Crime TV Shows
...,...,...,...,...,...,...,...,...,...,...
8805,s8806,Movie,Zoom,United States,2006,2020,1,PG,88.0,Children & Family Movies
8805,s8806,Movie,Zoom,United States,2006,2020,1,PG,88.0,Comedies
8806,s8807,Movie,Zubaan,India,2015,2019,3,TV-14,111.0,Dramas
8806,s8807,Movie,Zubaan,India,2015,2019,3,TV-14,111.0,International Movies
8806,s8807,Movie,Zubaan,India,2015,2019,3,TV-14,111.0,Music & Musicals

In [56]:
df_final["listed_in"].value_counts()

listed_in
International Movies            3509
Dramas                          3199
Comedies                        1981
International TV Shows          1464
Action & Adventure              1182
Documentaries                   1116
Independent Movies              1040
TV Dramas                        851
Children & Family Movies         845
Thrillers                        806
Romantic Movies                  722
TV Comedies                      623
Kids' TV                         594
Crime TV Shows                   540
Horror Movies                    458
Docuseries                       435
Music & Musicals                 429
Romantic TV Shows                384
Sci-Fi & Fantasy                 380
Stand-Up Comedy                  344
British TV Shows                 305
Reality TV                       270
Sports Movies                    265
TV Action & Adventure            203
Spanish-Language TV Shows        201
Anime Series                     191
Korean TV Shows                  156
Classic Movies                   151
LGBTQ Movies                     116
TV Mysteries                     113
Science & Nature TV              108
TV Sci-Fi & Fantasy              100
Cult Movies                       93
Faith & Spirituality              89
TV Horror                         86
Anime Features                    78
Movies                            70
Teen TV Shows                     69
TV Thrillers                      66
Stand-Up Comedy & Talk Shows      56
Classic & Cult TV                 30
TV Shows                          16
Name: count, dtype: int64

In [64]:
df2= pd.read_csv("fact_table.csv")

In [65]:
df2

,Show_ID,Type,Title,Country,Release_Year,Year_Added,Month_Added,Rating,Duration,Genre
0,s1,Movie,Dick Johnson Is Dead,United States,2020,2021,9,PG-13,90.0,Documentaries
1,s2,TV Show,Blood & Water,South Africa,2021,2021,9,TV-MA,2.0,International TV Shows
2,s2,TV Show,Blood & Water,South Africa,2021,2021,9,TV-MA,2.0,TV Dramas
3,s2,TV Show,Blood & Water,South Africa,2021,2021,9,TV-MA,2.0,TV Mysteries
4,s3,TV Show,Ganglands,Unknown,2021,2021,9,TV-MA,1.0,Crime TV Shows
...,...,...,...,...,...,...,...,...,...,...
23729,s8806,Movie,Zoom,United States,2006,2020,1,PG,88.0,Children & Family Movies
23730,s8806,Movie,Zoom,United States,2006,2020,1,PG,88.0,Comedies
23731,s8807,Movie,Zubaan,India,2015,2019,3,TV-14,111.0,Dramas
23732,s8807,Movie,Zubaan,India,2015,2019,3,TV-14,111.0,International Movies
23733,s8807,Movie,Zubaan,India,2015,2019,3,TV-14,111.0,Music & Musicals

In [66]:
df2.isnull().sum()

Show_ID         0
Type            0
Title           0
Country         5
Release_Year    0
Year_Added      0
Month_Added     0
Rating          0
Duration        3
Genre           0
dtype: int64

In [67]:
df2["Country"] = df2["Country"].fillna("Unknown")
df2["Duration"] = df2["Duration"].fillna("Not Available")

In [68]:
df2.isnull().sum()

Show_ID         0
Type            0
Title           0
Country         0
Release_Year    0
Year_Added      0
Month_Added     0
Rating          0
Duration        0
Genre           0
dtype: int64

In [69]:
df2.to_csv("Fact.csv")